/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fornularios;

import dao.DaoAusencia;
import dao.DaoDocente;
import dao.DaoEstudiante;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Freedman
 */
public class Buscarestudiante extends javax.swing.JFrame {
    private final DaoEstudiante daoE = new DaoEstudiante();
    private final DaoAusencia daoA =  new DaoAusencia();
    private final DaoDocente daoD = new DaoDocente();
    private final int IdDocente;
    private boolean idActivado = false;
    
    
    /**
     * Creates new form Buscarestudiante
     * @param IdD
     */
    public Buscarestudiante(int IdD) {
        initComponents();
        IdDocente = IdD;
        this.cargarEstudiantes();
    }

    private void cargarEstudiantes(){
        DefaultListModel<String> model = new DefaultListModel<>();
        for(int i = 0; i < daoE.getListaEstudiante().size(); i++){
            model.addElement(daoE.getListaEstudiante().get(i).getNombre() + 
                    daoE.getListaEstudiante().get(i).getApellido());
            
        }
        JLEstudiantes.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIntroducir = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLEstudiantes = new javax.swing.JList<>();
        btnEliminar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BUSCAR ESTUDIANTE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Introduce el ID");

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cheque.png"))); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(JLEstudiantes);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/boton-eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reporte.png"))); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/regreso.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(btnOk))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(btnRegresar)))))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menuausencia abrir = new Menuausencia(IdDocente);
        abrir.setVisible(true);
        this.setVisible(false); 
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(!idActivado){
            int idEst = JLEstudiantes.getSelectedIndex();
            String fecha = JOptionPane.showInputDialog(null, "Ingrese la nueva "
                    + "fecha de esta ausencia: ", 
                    "Ausencia", JOptionPane.INFORMATION_MESSAGE );
            String mes = JOptionPane.showInputDialog(null, "Ingrese el nuevo "
                    + "mes de esta ausencia: ", 
                    "Ausencia", JOptionPane.INFORMATION_MESSAGE );
            String year = JOptionPane.showInputDialog(null, "Ingrese el nuevo "
                    + "año de esta ausencia: ", 
                    "Ausencia", JOptionPane.INFORMATION_MESSAGE );
            
            int IdE = daoA.getListaAusencia().get(idEst).getIdEstudiante();
            String clase = daoD.buscarDocente(IdDocente).getClaseImpartida();
            
            int IDM = daoA.getGreaterID();
            
            daoA.modificarAusencia(IDM + 1, year, mes, fecha, idEst, clase);
            
        }
        else{
            int idEst = Integer.parseInt(txtIntroducir.getText());
            String fecha = JOptionPane.showInputDialog(null, "Ingrese la nueva "
                    + "fecha de esta ausencia: ", 
                    "Ausencia", JOptionPane.INFORMATION_MESSAGE );
            String mes = JOptionPane.showInputDialog(null, "Ingrese el nuevo "
                    + "mes de esta ausencia: ", 
                    "Ausencia", JOptionPane.INFORMATION_MESSAGE );
            String year = JOptionPane.showInputDialog(null, "Ingrese el nuevo "
                    + "año de esta ausencia: ", 
                    "Ausencia", JOptionPane.INFORMATION_MESSAGE );
            
            int IdE = daoA.getListaAusencia().get(idEst).getIdEstudiante();
            String clase = daoD.buscarDocente(IdDocente).getClaseImpartida();
            
            daoA.modificarAusencia(0, year, mes, fecha, idEst, clase);
        }
        daoA.BDactualizar();
        idActivado = false;
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(!idActivado){
            int idEst = JLEstudiantes.getSelectedIndex();
            
            int IdA = daoA.getListaAusencia().get(idEst).getIdAusencia();
            String clase = daoD.buscarDocente(IdDocente).getClaseImpartida();
            
            daoA.eliminarAusencia(IdA);
            
        }
        else{
            int idEst = Integer.parseInt(txtIntroducir.getText());
            
            int IdA = daoA.getListaAusencia().get(idEst).getIdAusencia();
            String clase = daoD.buscarDocente(IdDocente).getClaseImpartida();
            
            daoA.eliminarAusencia(IdA);
        }
        daoA.BDactualizar();
        idActivado = false;
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        if(!idActivado){
            int idEst = JLEstudiantes.getSelectedIndex();
            
            int IdA = daoA.getListaAusencia().get(idEst).getIdAusencia();
            String clase = daoD.buscarDocente(IdDocente).getClaseImpartida();
            
            String msn =  daoA.buscarAusencia(IdA).getFecha()+
                    daoA.buscarAusencia(IdA).getMes() + 
                    daoA.buscarAusencia(IdA).getYear();
            
            JOptionPane.showMessageDialog(null, "Este estudiante tuvo una ausencia: "
            + msn);
        }
        
        else{
            int idEst = Integer.parseInt(txtIntroducir.getText());
            
            int IdA = daoA.getListaAusencia().get(idEst).getIdAusencia();
            String clase = daoD.buscarDocente(IdDocente).getClaseImpartida();
            
            String msn =  daoA.buscarAusencia(IdA).getFecha()+
                    daoA.buscarAusencia(IdA).getMes() + 
                    daoA.buscarAusencia(IdA).getYear();
            
            JOptionPane.showMessageDialog(null, "Este estudiante tuvo una ausencia: "
            + msn);
        }
        daoA.BDactualizar();
        idActivado = false;
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        idActivado = true;
        
     
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JLEstudiantes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIntroducir;
    // End of variables declaration//GEN-END:variables
}
